# Generated by Django 5.0.6 on 2024-08-01 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeterPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mpan",
                    models.CharField(
                        help_text="The unique national reference for a Metering System or an Asset Metering System.",
                        max_length=13,
                        verbose_name="MPAN Core",
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("F", "Failed"),
                            ("U", "Not validated"),
                            ("V", "Validated"),
                        ],
                        help_text="Indicates whether readings or Half Hourly advances have been validated for BSC Settlement, passed BSC Validation or failed BSC Validation.",
                        max_length=1,
                        verbose_name="Validation Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_id",
                    models.CharField(
                        help_text="The serial number which is stamped onto the meter nameplate at manufacture, which is used as the main identifier of a Meter.",
                        max_length=10,
                        verbose_name="Meter Id (Serial Number)",
                    ),
                ),
                (
                    "reading_type",
                    models.CharField(
                        choices=[
                            ("A", "Actual Change of Supplier Read"),
                            ("C", "Customer own read"),
                            (
                                "D",
                                "Deemed (Settlement Registers) or Estimated (Non-Settlement Registers)",
                            ),
                            ("F", "Final"),
                            ("I", "Initial"),
                            ("M", "MAR"),
                            ("O", "Old Supplier's Estimated CoS Reading"),
                            ("P", "Electronically collected via PPMIP"),
                            ("Q", "Meter Reading modified manually by DC"),
                            ("R", "Routine"),
                            ("S", "Special"),
                            ("T", "Proving Test Reading"),
                            ("U", "Forward Migration CoA"),
                            ("V", "Forward Migration CoS"),
                            ("W", "Withdrawn"),
                            ("X", "Supplier Agreed Switch Read"),
                            ("Y", "Reverse Migration CoS"),
                            ("Z", "Actual Change of Tenancy Read"),
                        ],
                        help_text="A code identifying the type of reading.",
                        max_length=1,
                        verbose_name="Rading Type",
                    ),
                ),
                (
                    "meter_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="energy.meterpoint",
                        verbose_name="Meter Point",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_register_id",
                    models.CharField(
                        help_text="The reference Id for a Meter Register within a meter.",
                        max_length=2,
                        verbose_name="Meter Register Id",
                    ),
                ),
                (
                    "reading_at",
                    models.DateTimeField(
                        help_text="The date and time at which a meter register reading is taken. The time is always midnight for Non-Half Hourly readings with the exception of *special* reads where the absolute reading time must be given.",
                        verbose_name="Reading Date & Time",
                    ),
                ),
                (
                    "register_reading",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="The value of a reading from a meter register at a specified date and time.",
                        max_digits=10,
                        verbose_name="Register Reading",
                    ),
                ),
                (
                    "md_reset_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time at which a Maximum Demand Meter is reset to zero.",
                        null=True,
                        verbose_name="MD Reset Date & Time",
                    ),
                ),
                (
                    "number_md_resets",
                    models.PositiveSmallIntegerField(
                        help_text="The number of times that the Maximum Demand Indicator has been reset.",
                        verbose_name="Number of MD Resets",
                    ),
                ),
                (
                    "meter_reading_flag",
                    models.CharField(
                        choices=[("T", "Valid"), ("F", "Suspect")],
                        help_text="Indicates whether register reading is valid or suspect.",
                        max_length=1,
                        verbose_name="Meter Reading Flag",
                    ),
                ),
                (
                    "reading_method",
                    models.CharField(
                        choices=[
                            ("N", "Not viewed by an Agent or Non Site Visit"),
                            ("P", "Viewed by an Agent or Site Visit"),
                        ],
                        help_text="Indicates how the meter reading was obtained",
                        max_length=1,
                        verbose_name="Reading Method",
                    ),
                ),
                (
                    "flow_file",
                    models.CharField(
                        help_text="The filename of the flow file that the reading came in",
                        max_length=100,
                        verbose_name="Flow File",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="energy.meter",
                        verbose_name="Meter",
                    ),
                ),
            ],
        ),
    ]
