# Generated by Django 5.0.6 on 2024-07-31 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="Name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Address"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Contact email",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnergyConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("consumption_kwh", models.FloatField(verbose_name="Consumption Kwh")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("solar", "Solar"),
                            ("wind", "Wind"),
                            ("grid", "Grid"),
                        ],
                        max_length=6,
                        verbose_name="Source",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumptions",
                        to="energy.business",
                    ),
                ),
            ],
            options={
                "unique_together": {("business", "date", "source")},
            },
        ),
    ]
