# Generated by Django 5.0.6 on 2024-08-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time at which a file has been imported",
                        verbose_name="Import Date & Time",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the .uff file",
                        max_length=50,
                        verbose_name="File name",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of the imported file",
                        verbose_name="File Content",
                    ),
                ),
            ],
        ),
    ]
